import { BarChart3, Download, FileCheck2, FileSpreadsheet, Filter } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'react-hot-toast'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'

const reportCards = [
  {
    title: 'Attendance Summary',
    subtitle: 'Weekly and monthly trend report',
    type: 'PDF',
    generated: '2h ago',
    icon: BarChart3,
  },
  {
    title: 'Payroll Compliance',
    subtitle: 'Tax and deductions verification',
    type: 'CSV',
    generated: 'Today, 08:24',
    icon: FileCheck2,
  },
  {
    title: 'Employee Masterlist',
    subtitle: 'Department and role listing',
    type: 'XLSX',
    generated: 'Yesterday',
    icon: FileSpreadsheet,
  },
]

const recentExports = [
  { name: 'Q1 Attendance Audit', owner: 'Maya Watson', date: 'Apr 04, 2026', size: '1.8 MB' },
  { name: 'March Payroll Register', owner: 'Andre Lim', date: 'Apr 01, 2026', size: '2.4 MB' },
  { name: 'Employee Leave Ledger', owner: 'Lea Santos', date: 'Mar 30, 2026', size: '1.1 MB' },
]

function downloadTextFile(fileName: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

export default function Reports() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [showFilters, setShowFilters] = useState(false)
  const [ownerFilter, setOwnerFilter] = useState('All')
  const [query, setQuery] = useState('')

  const owners = useMemo(
    () => ['All', ...new Set(recentExports.map((row) => row.owner))],
    [],
  )

  const filteredExports = useMemo(() => {
    const q = query.trim().toLowerCase()
    return recentExports.filter((row) => {
      const ownerMatch = ownerFilter === 'All' || row.owner === ownerFilter
      const queryMatch =
        q === '' ||
        [row.name, row.owner, row.date, row.size].join(' ').toLowerCase().includes(q)
      return ownerMatch && queryMatch
    })
  }, [ownerFilter, query])

  const handleFilters = () => {
    setShowFilters(true)
  }

  const handleExportCenter = () => {
    if (filteredExports.length === 0) {
      toast.error('No rows to export.')
      return
    }

    const header = 'Report Name,Generated By,Date,File Size'
    const rows = filteredExports.map((row) =>
      [row.name, row.owner, row.date, row.size].map((value) => `"${value}"`).join(','),
    )
    downloadTextFile('reports-export.csv', [header, ...rows].join('\n'))
    toast.success('Exported reports CSV.')
  }

  const handleDownload = (name: string) => {
    const content = [
      `Report: ${name}`,
      `Generated at: ${new Date().toISOString()}`,
      'Status: Completed',
    ].join('\n')
    downloadTextFile(`${name.replace(/\s+/g, '-').toLowerCase()}.txt`, content)
    toast.success(`Downloaded ${name}.`)
  }

  useEffect(() => {
    if (searchParams.get('quickAdd') === 'filters') {
      setShowFilters(true)
      setSearchParams({}, { replace: true })
    }
  }, [searchParams, setSearchParams])

  return (
    <div className="page-enter space-y-6">
      <section className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="font-display text-3xl tracking-tight text-slate-900">Reports</h2>
          <p className="mt-1 text-sm text-slate-600">
            Generate operational, payroll, and compliance exports.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            className="h-10 rounded-xl border border-slate-300 bg-white px-4 text-slate-700 hover:bg-slate-100"
            onClick={handleFilters}
          >
            <Filter className="mr-2 h-4 w-4" />
            Filters
          </Button>
          <Button
            className="h-10 rounded-xl bg-slate-900 px-4 text-white hover:bg-slate-800"
            onClick={handleExportCenter}
          >
            <Download className="mr-2 h-4 w-4" />
            Export Center
          </Button>
        </div>
      </section>

      <section className="stagger-children grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {reportCards.map((card) => {
          const Icon = card.icon
          return (
            <article className="surface-card surface-card-hover p-5" key={card.title}>
              <div className="flex items-center justify-between">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-700">
                  <Icon className="h-5 w-5" />
                </div>
                <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">
                  {card.type}
                </span>
              </div>
              <h3 className="mt-3 text-base font-semibold text-slate-900">{card.title}</h3>
              <p className="mt-1 text-sm text-slate-600">{card.subtitle}</p>
              <p className="mt-3 text-xs text-slate-500">Last generated: {card.generated}</p>
            </article>
          )
        })}
      </section>

      <section className="surface-card surface-card-hover p-5">
        <div className="mb-4 flex items-center justify-between">
          <h3 className="text-lg font-semibold text-slate-900">Recent Exports</h3>
          <p className="text-sm text-slate-500">Last 7 days</p>
        </div>

        <div className="overflow-x-auto">
          <div className="max-h-[60vh] overflow-y-auto">
            <table className="w-full min-w-[720px] text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-xs uppercase tracking-[0.1em] text-slate-500">
                <th className="px-3 py-3 font-semibold">Report Name</th>
                <th className="px-3 py-3 font-semibold">Generated By</th>
                <th className="px-3 py-3 font-semibold">Date</th>
                <th className="px-3 py-3 font-semibold">File Size</th>
                <th className="px-3 py-3 text-right font-semibold">Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredExports.map((row) => (
                <tr className="border-b border-slate-100 hover:bg-slate-50/70" key={row.name}>
                  <td className="px-3 py-3 font-medium text-slate-900">{row.name}</td>
                  <td className="px-3 py-3 text-slate-700">{row.owner}</td>
                  <td className="px-3 py-3 text-slate-700">{row.date}</td>
                  <td className="px-3 py-3 text-slate-700">{row.size}</td>
                  <td className="px-3 py-3 text-right">
                    <button
                      className="rounded-lg px-3 py-1.5 text-xs font-semibold text-sky-700 transition hover:bg-sky-50"
                      onClick={() => handleDownload(row.name)}
                      type="button"
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
            </table>
          </div>
        </div>
      </section>

      {showFilters ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
          <button
            aria-label="Close modal"
            className="absolute inset-0 bg-slate-950/45 backdrop-blur-[2px]"
            onClick={() => setShowFilters(false)}
            type="button"
          />

          <div className="relative z-10 w-full max-w-md hrms-slide-up overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_60px_rgba(15,23,42,0.25)]">
            <div className="border-b border-slate-100 px-5 py-4">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h3 className="text-xl font-semibold tracking-tight text-slate-900">Report Filters</h3>
                  <p className="mt-1 text-xs text-slate-500">Refine export list by owner and search text.</p>
                </div>
                <button
                  aria-label="Close"
                  className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-slate-200 text-slate-500 transition hover:bg-slate-100 hover:text-slate-700"
                  onClick={() => setShowFilters(false)}
                  type="button"
                >
                  x
                </button>
              </div>
            </div>

            <div className="space-y-3 px-5 py-4">
              <div>
                <label className="mb-1 block text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Generated By</label>
                <select
                  className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none transition focus:border-sky-400"
                  onChange={(e) => setOwnerFilter(e.target.value)}
                  value={ownerFilter}
                >
                  {owners.map((owner) => (
                    <option key={owner} value={owner}>
                      {owner}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="mb-1 block text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Search</label>
                <input
                  className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none transition focus:border-sky-400"
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Report name, owner, date, size"
                  type="text"
                  value={query}
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 border-t border-slate-100 px-5 py-4">
              <button
                className="h-10 rounded-lg border border-slate-200 bg-white px-4 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
                onClick={() => {
                  setOwnerFilter('All')
                  setQuery('')
                }}
                type="button"
              >
                Reset
              </button>
              <button
                className="h-10 rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white transition hover:bg-slate-800"
                onClick={() => {
                  setShowFilters(false)
                  toast.success(`Applied filters (${filteredExports.length} results).`)
                }}
                type="button"
              >
                Apply Filters
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}
